name: Add Event
description: Add a new community event
title: '[Event]: '
labels:
- event
body:
- type: input
  id: title
  attributes:
    label: Event Title
    description: The name of the event
    placeholder: 'ex: Meetup AWS re:Invent re:Cap'
  validations:
    required: true
- type: input
  id: date
  attributes:
    label: Event Date
    description: When will the event take place? (YYYY-MM-DD HH:mm)
    placeholder: 2025-02-20 18:30
  validations:
    required: true
- type: input
  id: url
  attributes:
    label: Event URL
    description: Link to the event page
    placeholder: https://www.meetup.com/...
  validations:
    required: true
- type: dropdown
  id: community
  attributes:
    label: Community
    description: Select the organizing community
    options:
    - afup-bordeaux
    - agile-bordeaux
    - agile-tour-bordeaux
    - apero-web
    - aperops-dataops-mlops
    - aquilenet
    - aquinum
    - archilocus
    - aws-bordeaux
    - bdx-io
    - bdx-testing-community
    - bordeaux-python-meetup
    - bordeaux-xr
    - bordeauxjs
    - bordeauxjug
    - bordeauxkt
    - cafe-ia
    - cloud-native-bordeaux
    - creative-coding-bordeaux
    - data-for-good
    - digitalnights
    - framer-bordeaux
    - france-design-week-bordeaux
    - friends-of-figma-bordeaux
    - grappe-numerique
    - human-talks
    - la-boussole-de-la-tech
    - le-nom-lieu
    - mtg-bordeaux
    - okiwi
    - openstreetmap-bordeaux
    - serious-gamers-bordeaux
    - women-in-tech-bordeaux
  validations:
    required: true
- type: input
  id: location
  attributes:
    label: Location
    description: Ou se déroulera l'évènement ? 
    placeholder: Le node, 12 Rue des Faussets, 33000 Bordeaux
  validations:
    required: true
- type: textarea
  id: description
  attributes:
    label: Description
    description: Description de l'évènement (supports markdown)
    placeholder: Cet évènement exceptionnel....
  validations:
    required: false
- type: dropdown
  id: is_online
  attributes:
    label: Is this an online event?
    options:
    - 'No'
    - 'Yes'
  validations:
    required: true
